<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii translation' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Error executing query. OSRM server returned HTTP code {code}. Request was {req}' => 'Došlo k chybě při provádění dotazu. Server OSRM vrátil kód {code}. Požadavek byl {req}',
  'No coordinates specified.' => 'Nebyly zadány žádné souřadnice.',
  'No nearest point found.' => 'Nebyl nalezen žádný nejbližší bod.',
  'No route found.' => 'Nebyla nalezena žádná trasa.',
  'Unexpected server reply.' => 'Neočekávaná odpověď serveru.',
  'Unknown OSRM status code {code}. Request was {req}' => 'Neznámý stavový kód OSRM {code}. Požadavek byl {req}',
);
